basePath: /
host: api.eirc.app
info:
  contact:
    email: mingzong.lyu@gmail.com
    name: API System Support
    url: https://eirc.app/
  description: 企業系統整合管理平台
  license:
    name: AGPL 3.0
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
  termsOfService: https://eirc.app/
  title: hsmaster SYSTEM API
  version: "0.1"
paths: {}
schemes:
- https
swagger: "2.0"
